import { createTheme } from '@mui/material';

export const defaultTheme = createTheme({
  typography: {
    fontFamily: 'Roboto',
    title: {
      fontSize: '24px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color: '#000000',
    },
    subtitle: {
      fontSize: '24px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color: '#000000',
    },
    balance: {
      fontSize:  '30px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: 'normal',
      color:'#FFFFFF',
    },
    balanceTitle: {
      fontSize:  '18px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#FAFAFA',
    },
    cardDigits: {
      fontSize:  '18px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#A3A3A3',
      marginRight: '16px',
    },
    selectItem: {
      fontSize:  '13px',
      fontStyle: 'normal',
      fontWeight: 401,
      lineHeight: 'normal',
      color:'#FFFFFF',
    },
    expandBtnText: {
      fontSize:  '12px',
      fontStyle: 'normal',
      fontWeight: 401,
      lineHeight: 'normal',
      width:'max-content',
      color:'#A3A3A3',
    },
    userName: {
      fontSize:  '16px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#000000',
    },
    greenAmount: {
      fontSize:  '18px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#2BB272',
    },
    blackAmount: {
      fontSize:  '18px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#000000',
    },
    calendarWeek: {
      fontSize:  '16px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#000000',
    },
    dayName: {
      fontSize:  '16px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#615C5C',
    },
    cardCaption: {
      fontSize:  '14px',
      fontStyle: 'normal',
      fontWeight: 401,
      lineHeight: 'normal',
      color:'#000000',
    },
    expensesTotalBalance:{
      fontSize:  '16px',
      fontStyle: 'normal',
      fontWeight: 501,
      lineHeight: 'normal',
      color:'#FFFFFF',
    },
    expensesTotalBalanceValue:{
      fontSize:  '28px',
      fontStyle: 'normal',
      fontWeight: 700,
      lineHeight: 'normal',
      color:'#FFFFFF',
    },
    expensesSubtitle:{
      fontSize:  '16px',
      fontStyle: 'normal',
      fontWeight: 401,
      lineHeight: 'normal',
      color:'#615C5C',
    },
  },
});
